### ISSUE TITLE
Unable to upload "image-scan/sarif.json" as it is not valid SARIF: instance.runs[0].tool.driver.rules contains duplicate item

### ISSUE THREAD

**Issue by b4st1en** [maratsal/playground#1]
Hello,

We've recently noticed that the python scipt for generating SARIF, which has worked very well until now, seems to have a problem.

Please find the GitHub workflow logs attached, for a public image:

- [11_SARIF Report (NewEngine).txt](https://github.com/maratsal/playground/files/13163775/11_SARIF.Report.NewEngine.txt)
- [14_SARIF Upload to GitHub Security tab.txt](https://github.com/maratsal/playground/files/13163776/14_SARIF.Upload.to.GitHub.Security.tab.txt)

Here are the output files:
- Sysdig New Engine output: [report.json](https://github.com/maratsal/playground/files/13174416/report.json)
- the generated SARIF: [sarif.json](https://github.com/maratsal/playground/files/13174419/sarif.json)

It seems that the CodeQL GitHub action cannot import the generated SARIF anymore..

Could you please check if you could do something ?

Kind Regards

**Comment by maratsal** [comment]
hi @b4st1en 

can you please share generated Sysdig and SARIF report as well. I want to see why I get duplicates. Also this one was my playground and we posted this script example to official repo. As soon as I will figure out the issue I will post updates there - https://github.com/sysdiglabs/secure-inline-scan-examples/blob/main/github/new-scan-engine/sysdig-to-sarif.py

**Comment by b4st1en** [comment]
Hello @maratsal !

Yes, please find both reports attached :
- Sysdig New Engine output: [report.json](https://github.com/maratsal/playground/files/13174416/report.json)
- the generated SARIF: [sarif.json](https://github.com/maratsal/playground/files/13174419/sarif.json)

Thanks for your help !

_PS: first comment updated as well._

Kind Regards

**Comment by maratsal** [comment]
@b4st1en I finally got some time to look at this, but when I download files they are empty. can you please reattach them?

Thanks

**Comment by maratsal** [comment]
never mind, I actually realized that image was publicly available one. I am looking at the issue and will post results soon.

**Comment by maratsal** [comment]
at the end it was one check that was in the code, but I forgot to append CVE id to list of added rules and because of that it was adding multiple IDs with the same name. You can use updated script form this repo.
